## **Aim**
Hands-on Python Programming for Applied Machine Learning with NumPy for Data Representation and Numerical Computations.

### **Exercise 1.1: Creating a Vector**
**Problem:**  
You need to create a vector.

In [11]:
import numpy as np

vector_row = np.array([10,20,30,40,50])
print(f"Row vector :{vector_row}")

vector_col = np.array([[10],[20],[30],[40],[50]])
print(f"Column vector :{vector_col}")

Row vector :[10 20 30 40 50]
Column vector :[[10]
 [20]
 [30]
 [40]
 [50]]


### **Exercise 1.2: Creating a Matrix**
**Problem:**  
You need to create a matrix.

In [14]:
import numpy as np

show_matrix = np.array([[25,3,32],
                        [43,94,23],
                        [12,21,98]])
print(show_matrix)


[[25  3 32]
 [43 94 23]
 [12 21 98]]


### **Exercise 1.3: Creating a Sparse Matrix**
**Problem:**  
Create a sparse matrix.

In [7]:
import numpy as np
from scipy import sparse
matrix = np.array([[0,2],
                 [3,0],
                 [1,0],
                 [0,5]])
sparse_matrix = sparse.csr_matrix(matrix)
print(sparse_matrix)


large_matrix = np.array([[0,1,0,0,0,0,0,0],
                         [0,4,0,0,0,0,0,0],
                         [9,0,0,0,0,0,0,0]])
                 
sparse_matrix_lg = sparse.csr_matrix(large_matrix)
print(sparse_matrix_lg)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (4, 2)>
  Coords	Values
  (0, 1)	2
  (1, 0)	3
  (2, 0)	1
  (3, 1)	5
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 8)>
  Coords	Values
  (0, 1)	1
  (1, 1)	4
  (2, 0)	9


A sparse matrix is a way to store large matrices that have mostly zero values efficiently. scipy.sparse.csr_matrix() only stores the non-zero values with their row and column positions, which saves memory and speeds up operations on big datasets.

### **Exercise 1.4: Selected Elements**
**Problem:**  
You need to select one or more elements in a vector or matrix.

In [1]:
import numpy as np
#create a row vector
row_vector = np.array([25,10,31,27,88,99])
print(row_vector[5])


99


In [2]:

#create a matrix 
matrix = np.array([[1,3,4],
                   [4,2,1],
                   [6,7,2],
                   [9,3,1]])
print(matrix[3,1])

3


In [4]:
#select all elements of vector
row_vector[:]

array([25, 10, 31, 27, 88, 99])

In [10]:
# Get elements from index 0 up to (but not including) index 2
row_vector[:2]

array([25, 10])

In [12]:
#select last element of vector
print(row_vector[-1])

99


In [16]:
#select first n rows (0 to n-1) and all columns
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160],
    [170, 180, 190, 200]
])

# Number of rows to select
n = 3 
# Select first n rows and all columns
first_n_rows = arr[:n, :]

print(first_n_rows)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [18]:
# Select all rows and columns from index 1 to 2 (1:3 → includes 1 and 2, excludes 3)
n_column = arr[:,1:3]
print(n_column)

[[ 20  30]
 [ 60  70]
 [100 110]
 [140 150]
 [180 190]]


### **Exercise 1.5: Describing Matrix**
**Problem:**  
You have to describe the shape, size and dimension of the matrix.

In [40]:
import numpy as np
x = np.array([[[1,2,1],[1,3,2],[1,3,2]]])
#Size of matrix
print(x.size)
#view no. of rows and columns
print(x.shape)
#view number of dimensions
print(x.ndim)

9
(1, 3, 3)
3


x.size gives the total number of elements. x.shape returns the arrangement of rows and columns (and depth for higher dimensions). x.ndim shows how many dimensions the array has.

### **Exercise 1.6:Applying operations to elements**
**Problem:**  
You have to apply some functions to multiple elements in the array.

In [43]:
import numpy as np
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
#create function which multiply 200 to all elements of the matrix
mul_200 = lambda i:i*200
#vectorized function
vectorized_mul_200 = np.vectorize(mul_200)
#apply function to all elememts in matrix
vectorized_mul_200(matrix)

array([[ 200,  400,  600],
       [ 800, 1000, 1200],
       [1400, 1600, 1800]])

In [45]:
# add 1000 to all elements
matrix + 3000

array([[3001, 3002, 3003],
       [3004, 3005, 3006],
       [3007, 3008, 3009]])

### **Exercise 1.7:Finding Maximum and Minimum values**
**Problem:**  
You need to find minimum or maximum value in an array.

In [3]:
import numpy as np
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
#maximum element
print(np.max(matrix))

9


In [4]:
#minimum element
print(np.min(matrix))

1


In [5]:

print(np.max(matrix,axis = 0))

[7 8 9]


finding maximum element in each column

In [50]:
#finding minimum element in each row
print(np.min(matrix,axis = 1))

[1 4 7]


finding maximum element in each row

### **Exercise 1.8: Calculating the Average, Variance and Standard Deviation**
**Problem:**  
You need to calculate some descriptive statistics about an array.

In [60]:
import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160],
    [170, 180, 190, 200]
])
#calculating mean
mean = int(np.mean(arr))
print(f"Mean: {mean}\n")

#calculating variance
variance = int(np.var(arr))
print(f"Variance: {variance}\n")

#calculating standard deviation
std = int(np.std(arr))
print(f"Standard Deviation: {std}\n")

#calculate mean in each column
print(np.mean(arr,axis = 0))

#calculate mean in each row
print(np.mean(arr,axis = 1))

Mean: 105

Variance: 3325

Standard Deviation: 57

[ 90. 100. 110. 120.]
[ 25.  65. 105. 145. 185.]


### **Exercise 1.9: Reshaping Arrays**
**Problem:**  
You need to change the shape (no. of rows and no. of columns) of an array without changing the element values.

In [88]:
import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160],
    [170, 180, 190, 200]
])
#reshape matrix into 10 x 2
arr.reshape(10,2)


array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100],
       [110, 120],
       [130, 140],
       [150, 160],
       [170, 180],
       [190, 200]])

The reshape() function changes the structure of the array without altering its data, as long as the total number of elements remains the same.

In [83]:
arr.reshape(-1,10)

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150, 160, 170, 180, 190, 200]])

reshape(-1,10) tells NumPy to automatically figure out the number of rows (-1) while fixing 10 columns. Since the array has 20 elements, it reshapes into a 2×10 matrix.

In [81]:
arr.reshape(5,-1)

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200]])

### **Exercise 1.10: Transposing a Vector or Matrix**
**Problem:**  
You need to transpose a vector or matrix.


In [98]:
import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160],
    [170, 180, 190, 200]
])
#transpose of given matrix
print(arr.T)

#transpose of vector
np.array([[1,3,4,5,5,2]]).T

[[ 10  50  90 130 170]
 [ 20  60 100 140 180]
 [ 30  70 110 150 190]
 [ 40  80 120 160 200]]


array([[1],
       [3],
       [4],
       [5],
       [5],
       [2]])

### **Exercise 1.11: Flattening a Matrix**
**Problem:**  
You need to transform a matrix into a one-dimensional array.

In [100]:
import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160],
    [170, 180, 190, 200]
])

#flatten matrix
print(arr.flatten())

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200]


It converts the 2D array into a 1D array using flatten(), which returns all elements in a single continuous list while preserving the row-wise order.

### **Exercise 1.12: Finding the Rank of a Matrix**
**Problem:**  
You need to know the rank of a matrix.

In [104]:
import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160],
    [170, 180, 190, 200]
])
#By using Numpy's linear algebra method
#rank of matrix 
rank = np.linalg.matrix_rank(arr)
print(f"Rank of matrix : {rank}")

Rank of matrix : 2


Numpy's Linear algebra function matrix_rank() to find the rank of the given 2D array. The rank represents the maximum number of linearly independent rows or columns in the matrix.

### **Exercise 1.13: Calculating the Determinant**
**Problem:**  
You need to know the determinant of a matrix.

In [113]:
import numpy as np

arr = np.array([
    [10,20,30],
    [50,60,70],
    [10,32,14]])
#calculating determinant of matrix

abs_det = round(np.abs(np.linalg.det(arr)))
print(f"Determinant of matrix: {abs_det}") 


Determinant of matrix: 16000


### **Exercise 1.14: getting the Diagonal of a Matrix**
**Problem:**  
You need to get the diagonal elements of matrix.

In [117]:
import numpy as np

arr = np.array([
    [10,20,30],
    [50,60,70],
    [10,32,14]])
#Diagonal Matrix
print(f"Diagonal Matrix: {arr.diagonal()}")

#Diagonal matrix one above the main diagonal
print(f"One above the main diagonal matrix:  {arr.diagonal(offset = 1)}")

#Diagonal matrix one below the main diagonal
print(f"One below the main diagonal matrix:  {arr.diagonal(offset = -1)}")

Diagonal Matrix: [10 60 14]
One above the main diagonal matrix:  [20 70]
One below the main diagonal matrix:  [50 32]


It extracts diagonal elements from a matrix using NumPy’s diagonal() method. With no offset, it returns the main diagonal, offset=1 gives the diagonal just above the main one, and offset=-1 gives the diagonal just below it.

### **Exercise 1.15: Calculating the Trace of a Matrix**
**Problem:**  
You need to know the trace of a matrix.

In [119]:
import numpy as np

arr = np.array([
    [43,11,83],
    [32,91,63],
    [10,76,14]])

#Trace of matrix (sum of diagonal elements)
print(f"Trace of matrix: {arr.trace()}")

Trace of matrix: 148


It calculates the trace of the matrix using trace(), which is the sum of its main diagonal elements (top-left to bottom-right).

### **Exercise 1.16: Finding Eigenvalues and Eigenvectors**
**Problem:**  
You need to find the eigenvalues and eigenvectors of a square matrix.

In [129]:
import numpy as np

arr = np.array([
    [-1,11,83],
    [32,3,63],
    [8,6,7]])
#Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(arr)
eigenvalues = np.real_if_close(eigenvalues)
print(f"Eigenvalues of given matrix :\n {eigenvalues}")


eigenvectors = np.real_if_close(eigenvectors)
print(f"Eigenvector of given matrix :\n {eigenvectors}")

Eigenvalues of given matrix :
 [ 46.6414452+0.j        -18.8207226+4.2932277j -18.8207226-4.2932277j]
Eigenvector of given matrix :
 [[ 0.58935851+0.j          0.5309721 -0.27853992j  0.5309721 +0.27853992j]
 [ 0.77266697+0.j         -0.79550874+0.j         -0.79550874-0.j        ]
 [ 0.2358862 +0.j          0.00583283+0.08726948j  0.00583283-0.08726948j]]


### **Exercise 1.17: Calculating Dot Products**
**Problem:**  
You need to calculate dot products of two vectors.

In [131]:
import numpy as np
vector_a = np.array([4,5,1,8])
vector_b = np.array([7,11,3,5])
#calculate dot product
print(np.dot(vector_a,vector_b))

126


### **Exercise 1.18: Adding and Subtracting Matrices**
**Problem:**  
You need to add or subtract two matrices.

In [134]:
import numpy as np

A = np.array([
    [4, 1, 1],
    [1, 3, 2],
    [1, 2, 3]
])
B = np.array([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 2]
])
#addition of two matrices
print(f"Addition of Matrices:\n {np.add(A,B)}")

#subtraction of two matrices
print(f"Subtraction of Matrices:\n {np.subtract(A,B)}")

Addition of Matrices:
 [[4 0 1]
 [2 3 2]
 [1 2 5]]
Subtraction of Matrices:
 [[4 2 1]
 [0 3 2]
 [1 2 1]]


### **Exercise 1.19: Multiplying Matrices**
**Problem:**  
You need to multiply two matrices.

In [135]:
import numpy as np

A = np.array([
    [4, 1, 1],
    [1, 3, 2],
    [1, 2, 3]
])
B = np.array([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 2]
])
#Multiplication of two matrices
print(f"Multiplication of Matrices:\n {np.dot(A,B)}")


Multiplication of Matrices:
 [[ 1 -4  2]
 [ 3 -1  4]
 [ 2 -1  6]]


### **Exercise 1.20: Inverting a Matrix**
**Problem:**  
You need to calculate the inverse of a square matrix.

In [137]:
import numpy as np

matrix = np.array([
    [4, 1, 1],
    [1, 3, 2],
    [1, 2, 3]
])
#Inverse of matrix
print(np.linalg.inv(matrix))


[[ 0.27777778 -0.05555556 -0.05555556]
 [-0.05555556  0.61111111 -0.38888889]
 [-0.05555556 -0.38888889  0.61111111]]


### **Exercise 1.21: Generating Random values**
**Problem:**  
You need to generate pseudorandom values.

In [143]:
import numpy as np
x = np.random.seed(0)
print(x)
print(np.random.random(3))
#generate 4 random integers between 1 to 7
print(np.random.randint(0,7,4))

None
[0.5488135  0.71518937 0.60276338]
[3 1 3 5]


This code sets a random seed (seed(0)) to make results reproducible, then generates random numbers: random(3) creates 3 random floats between 0 and 1, and randint(0,7,4) generates 4 random integers between 0 and 6.

**1. Import the numpy package under the name np**

In [1]:
import numpy as np

**2. Print the numpy version and the configuration**

In [4]:
print(f"numpy version: {np.__version__}")
print(f"Configuration : {np.show_config()}")

numpy version: 2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  cython:
    commands: cython
    linker: cytho

**3. Create a null vector of size 10.**

In [6]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. How to find the memory size of any array.**

In [2]:
import numpy as np
null_vector = np.zeros((5,5))
print("%d bytes"%(null_vector.size * null_vector.itemsize))

a = np.zeros((7,7), dtype=np.int32)
print("%d bytes"%(a.size * a.itemsize))

200 bytes
196 bytes


np.zeros((5,5)) creates a 5×5 array of zeros (default float64 → 8 bytes each). size gives total elements and itemsize gives bytes per element, so total = 25×8 = 200 bytes

**5. How to get the documentation of the numpy add function from command line**

**6. Create a null vector of size 10 but fifth value which is 1.**

In [18]:
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**7. Create a vector with values ranging from 10 to 49**

In [19]:
import numpy as np
range_vect = np.arange(10,49)
print(range_vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


**8. Reverse a vector (first element becomes last)**

In [21]:
import numpy as np
v = np.arange(20)
v = v[::-1]
print(v)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


**9. Create a 3x3 matrix with values ranging from 0 to 8.**

In [23]:
v = np.arange(9).reshape(3,3)   #reshapes them into a 3×3 matrix
print(v)  

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**10. Find indices of non-zero elements from [1,3,5,0,0,1,7,8,0]**

In [26]:
import numpy as np
non_zero = np.nonzero([1,3,5,0,0,1,7,8,0])
print(non_zero)

(array([0, 1, 2, 5, 6, 7]),)


**11. Create a 3x3 identity matrix.**

In [27]:
import numpy as np
v = np.eye(3)
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**12. Create a 3x3x3 matrix with random values**

In [29]:
import numpy as np
v = np.random.random((3,3,3))
print(v)

[[[0.78807073 0.57392128 0.94284193]
  [0.48888567 0.39918263 0.66193005]
  [0.53807412 0.36714451 0.28933846]]

 [[0.15855199 0.07286505 0.50425107]
  [0.04495392 0.68770411 0.31858053]
  [0.21322033 0.75594383 0.87597989]]

 [[0.66141613 0.91586679 0.08599965]
  [0.22997189 0.22666984 0.73139022]
  [0.07853546 0.48299007 0.33576908]]]


**13. Create a 10x10 array with random values and find the minimum and maximum values.**

In [33]:
import numpy as np
v = np.random.random((3,3,3))
print(v)
vMax,Vmin = v.max(),v.min()
print(f"Maximum value: {vMax}\nMinimum value: {v.min()}")

[[[0.47674164 0.6175253  0.79648268]
  [0.42305367 0.07370539 0.91584811]
  [0.77274101 0.81551943 0.81738522]]

 [[0.4985797  0.64517886 0.49046791]
  [0.37463971 0.66154444 0.83320884]
  [0.25896088 0.39348219 0.85352798]]

 [[0.0151865  0.65113539 0.75677411]
  [0.39372578 0.05827299 0.76707952]
  [0.47771294 0.19491807 0.19763621]]]
Maximum value: 0.9158481077963353
Minimum value: 0.015186497287631218


**14. Create a random vector with size 30 and find the mean value.**

In [35]:
import numpy as np
random_v = np.random.random(30)
mean_val = random_v.mean()
print(mean_val)

0.5022619646706814


**15. Create a 2D array with 1 on the border and 0 inside.**

In [39]:
import numpy as np
v = np.ones((15,15))
v[1:-1,1:-1]=0
print(v)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**16. How to add a border (filled with 0's) around an existing array?**

In [5]:
import numpy as np
v = np.ones((7,7))
v = np.pad(v,pad_width=2,mode='constant',constant_values = 0)
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**17. What is the result of the following expression?**

In [18]:
print(0*np.nan)

nan


In [19]:
print(np.nan == np.nan)

False


In [21]:
print(np.inf > np.nan)

False


In [22]:
print(np.inf)

inf


In [23]:
print(np.nan - np.nan)

nan


In [57]:
print(np.nan in set([np.nan]))

True


In [25]:
print(0.3 == 3*0.1)

False


In [26]:
print(np.nan)

nan


In [27]:
print(0.3)

0.3


In [28]:
print(3*0.1)

0.30000000000000004


In [29]:
print(np.inf>100000000)

True


**18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.**

In [36]:
import numpy as np
matrix = np.diag(1+np.arange(4),k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


**19. Create a 8x8 matrix and fill it with a checkerboard pattern.**

In [37]:
import numpy as np
v = np.zeros((8,8),dtype=int)
v[1::2,::2]=1
v[::2,1::2]=1
print(v)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element.**

In [40]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


**21. Create a checkerboard 8x8 matrix using the tile function.**

In [43]:
checker_board = np.tile(np.array([[0,1],[1,0]]),(8,8))
print(checker_board)

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


**22. Normalize a 5x5 random matrix.**

In [50]:
random_matrix = np.random.random((5,5))
print(random_matrix)
mean = np.mean(random_matrix)
std = np.std(random_matrix)
normalize = (random_matrix - mean)/std
print(f"Normalize matrix:\n{normalize}")

[[0.76055386 0.15203364 0.54474883 0.62372378 0.09124331]
 [0.02588216 0.69981229 0.24744537 0.36537469 0.92309213]
 [0.03174215 0.18141471 0.20535613 0.36527784 0.78807049]
 [0.16354088 0.71300382 0.42238291 0.29159333 0.75476171]
 [0.95453886 0.72805789 0.39015587 0.3594175  0.93313828]]
Normalize matrix:
[[ 0.99906329 -1.08367581  0.26044268  0.53074467 -1.29173857]
 [-1.51544558  0.79116743 -0.75711682 -0.35348848  1.55537153]
 [-1.49538898 -0.98311529 -0.9011727  -0.35381998  1.09324253]
 [-1.0442908   0.83631715 -0.1583705  -0.60601472  0.97923892]
 [ 1.66300206  0.88784164 -0.26867171 -0.37387774  1.58975578]]


**23. Given a 1D array, negate all elements which are between 3 and 8, in place.**

In [63]:
arr = np.arange(11)
print(arr)
a = arr[(3<arr) & (arr<=8)]
arr[a]*=-1
print(f"After negating all elements between 3 and 8:\n{arr}")

[ 0  1  2  3  4  5  6  7  8  9 10]
After negating all elements between 3 and 8:
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


**24. Consider an integer vector Z, which of these expressions are legal?**

In [69]:
Z=4
print(Z**Z)
print(2<<Z>>2)
print(Z<-Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

256
8
False
4j
4.0
False


**25. How to find common values between two arrays?.**

In [72]:
A = np.random.randint(0,15,10)
B = np.random.randint(0,15,10)
print(A)
print(B)
common_val = np.intersect1d(A,B)
print(common_val)

[ 2 10 11  6 10  8  3  3  0  3]
[11  8  4  2 12 12  1 11  8 10]
[ 2  8 10 11]


**26. How to get the dates of yesterday,today and tomorrow?**

In [85]:
#Today
today = np.datetime64('today','D')
print(f"Today: {today}")
#Yesterday
yesterday = today - np.timedelta64(1,'D')
print(f"Yesterday: {yesterday}")
#Tomorrow
tomorrow = today + np.timedelta64(1,'D')
print(f"Tomorrow: {tomorrow}")

Today: 2025-08-12
Yesterday: 2025-08-11
Tomorrow: 2025-08-13


**27. How to get all the dates corresponding to the month of July 2016?**

In [88]:
x = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


**28. Extract the integer part of a random array using 5 different methods.**

In [16]:
import numpy as np
arr = np.random.uniform(0,10,10)
print(arr)
print(arr%1)
#Method - 1
print(arr - arr%1)
#Method - 2
print(np.floor(arr))
#Method - 3
print(np.ceil(arr)-1)
#Method - 4
print(arr.astype(int))
#Method - 5
print(np.trunc(arr))

[0.88872887 7.73038552 9.97813431 3.45639145 0.23598239 9.27496033
 6.5742935  6.26267296 0.1740877  6.70971983]
[0.88872887 0.73038552 0.97813431 0.45639145 0.23598239 0.27496033
 0.5742935  0.26267296 0.1740877  0.70971983]
[0. 7. 9. 3. 0. 9. 6. 6. 0. 6.]
[0. 7. 9. 3. 0. 9. 6. 6. 0. 6.]
[0. 7. 9. 3. 0. 9. 6. 6. 0. 6.]
[0 7 9 3 0 9 6 6 0 6]
[0. 7. 9. 3. 0. 9. 6. 6. 0. 6.]


**29. Create a 5x5 matrix with row values ranging from 0 to 4.**

In [17]:
import numpy as np
arr = np.zeros((5,5))
arr += np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**30. Create a random vector of size 10 and sort it.**

In [19]:
import numpy as np 
v = np.random.random(10)
print(f"Before sorting : {v}")
v.sort()
print(f"After sorting : {v}")

Before sorting : [0.89046432 0.23839729 0.36466666 0.24048565 0.37111622 0.97589296
 0.88485158 0.97660951 0.56951192 0.96290982]
After sorting : [0.23839729 0.24048565 0.36466666 0.37111622 0.56951192 0.88485158
 0.89046432 0.96290982 0.97589296 0.97660951]


**31. Consider two random array A and B, check if they are equal.**

In [23]:
import numpy as np
A = np.random.randint(0,3,7)
B = np.random.randint(0,3,7)
print(np.allclose(A,B))
print(np.array_equal(A,B))

False
False


**32. Make an array immutable(read-only).**

In [32]:
import numpy as np
arr = np.arange(10)
arr.flags.writeable = False
print(arr)
#arr[1] = 5   

[0 1 2 3 4 5 6 7 8 9]


**33. Print the minimum and maximum representable value for each numpy scalar type.**

In [119]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


**34. How to find the closet value (to a given vector) in a vector?.**

In [37]:
import numpy as np
arr = np.arange(100)
print(arr)
v = np.random.uniform(0,100)
print(v)
idx = (np.abs(arr-v)).argmin()
print(arr[idx])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
90.47009622802074
90


**35. Consider a random vector with shape(100,2) representing coordinates, find point by point distances.**

In [43]:
import numpy as np
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt((X-X.T)**2+(Y-Y.T)**2)
print(D)

[[0.         0.52192386 0.36314589 ... 0.64438361 0.6008727  0.27558182]
 [0.52192386 0.         0.44275314 ... 0.29595667 0.54144652 0.42004195]
 [0.36314589 0.44275314 0.         ... 0.70317648 0.81802945 0.0895253 ]
 ...
 [0.64438361 0.29595667 0.70317648 ... 0.         0.32792379 0.65613316]
 [0.6008727  0.54144652 0.81802945 ... 0.32792379 0.         0.74341893]
 [0.27558182 0.42004195 0.0895253  ... 0.65613316 0.74341893 0.        ]]


**36. How to convert a float(32 bits) array into an integer (32 bits) in place?**

In [51]:
import numpy as np
X = np.arange(7,dtype = np.float32)
print(X)
X = X.astype(np.int32,copy = False)
print(X)

[0. 1. 2. 3. 4. 5. 6.]
[0 1 2 3 4 5 6]


**37. How to read the following file?**

In [62]:
from io import StringIO
import numpy as np
#fake file

s = StringIO("""1,2,3,4,5\n
                6, , ,7,8\n
                 , ,9,10,11\n""")
X = np.genfromtxt(s, delimiter=",",dtype=int)
print(X)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


**38. Subtract the mean of each row of a matrx.**

In [64]:
X = np.random.rand(5,10)
Y = X - X.mean(axis=1,keepdims=True)
print(Y)

[[ 0.03050522 -0.13974248  0.32388226  0.03313433  0.10888284 -0.47072539
  -0.10670633  0.38701573  0.12832585 -0.29457204]
 [ 0.21341949 -0.20502579 -0.08245712  0.11568067 -0.32855603 -0.2255129
  -0.28377351  0.46509397  0.54692354 -0.21579232]
 [-0.0416952   0.17075731  0.48093783 -0.33111057  0.12499858  0.10292589
   0.15913277 -0.31512002 -0.27952598 -0.07130061]
 [ 0.21087943  0.1911309   0.12882195  0.30589207 -0.52480439 -0.286494
   0.38633837  0.10380241 -0.47661536 -0.03895137]
 [-0.02523906 -0.36066686  0.01162482  0.35067316  0.57481863 -0.12297807
  -0.13578228 -0.24220835 -0.28729186  0.23704987]]


**39. How to sort an array by the nth column?**

In [78]:
import numpy as np
X = np.random.randint(0,25,(5,5))
print(X)  #5x5 matrix
print(X[X[:,2].argsort()]) #sort by 3rd column

[[ 9 16  8 15  3]
 [14 10  7 21  4]
 [10 11 20 17 19]
 [ 4 17  9 22 23]
 [17  2 19  1  8]]
[[14 10  7 21  4]
 [ 9 16  8 15  3]
 [ 4 17  9 22 23]
 [17  2 19  1  8]
 [10 11 20 17 19]]


**40. How to tell if a given 2D array has null columns?**

In [86]:
import numpy as np
X = np.random.randint(0,3,(4,10))
print(X)
print((~X.any(axis=0)).any())

[[0 0 2 0 1 0 0 2 2 1]
 [1 0 1 0 2 0 2 0 1 2]
 [1 2 1 1 1 1 2 0 2 1]
 [0 2 0 2 0 0 2 2 2 1]]
False


**41. Find the nearest value from a given value in an array.**

In [88]:
import numpy as np
arr = np.random.uniform(0,1,10)
print(arr)
x = 0.8
nearest_val = arr.flat[np.abs(arr-x).argmin()]
print(nearest_val)

[0.49957647 0.98945732 0.71788768 0.2394182  0.32913393 0.50834384
 0.07647152 0.87392349 0.16229282 0.83545684]
0.835456842253907


**42. How to accumulate elements of a vector (X) to an array (F) based on an index list(I)?**

In [91]:
import numpy as np
X = [1,2,3,4,5,6]
I = [1,3,7,5,2,1]
F = np.bincount(I,X)
print(F)


[0. 7. 5. 2. 0. 4. 0. 3.]


**43. How to get the diagonal of a dot product?**

In [9]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

#slow version
print(np.diag(np.dot(A,B)))
#fast version 
print(np.sum(A*B.T,axis=1))      #row wise dot products using element-wise multiplication with B transposed
#faster version
print(np.einsum("ij,ji->i",A,B))   #Einstein summation to extract only diagonal elements efficiently 

[2.08761354 1.4707435  1.46866618 0.72227404 1.01926084]
[2.08761354 1.4707435  1.46866618 0.72227404 1.01926084]
[2.08761354 1.4707435  1.46866618 0.72227404 1.01926084]


**44. Consider the vector[1,2,3,4,5], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [98]:
A = np.array([1,2,3,4,5])
nz = 3
B = np.zeros(len(A) + (len(A)-1)*(nz))
B[::nz+1] = A
print(B)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


**45. How to swap two rows of an array?**

In [99]:
X = np.arange(25).reshape(5,5)
X[[0,1]] = X[[1,0]]
print(X)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**46. How to compute averages using a sliding window over an array?**

In [101]:
import numpy as np
def sliding_avg(arr,size=3):
    cum_sum = np.cumsum(arr,dtype=float)
    cum_sum[size:] = cum_sum[size:] - cum_sum[:-size]
    return cum_sum[size - 1:]/size
data_arr = np.arange(20)
print(sliding_avg(data_arr,size=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


**47. Consider 2 sets of points P0,P1 describing lines (2D) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?**

In [102]:
import numpy as np

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:, 0] - p[..., 0]) * T[:, 0] + (P0[:, 1] - p[..., 1]) * T[:, 1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U * T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (1, 2))

print(distance(P0, P1, p))


[12.95280782  9.57917598  3.50319458  9.12133793  1.47530157  3.966637
  5.73514552  2.91420055  0.24372168  9.27973251]


**48. Consider 2 sets of points P0,P1 describing lines (2D) and a set of points P, how to compute distance from each point j (P[j]) to each line i  (P0[i],P1[i])?**

In [103]:

P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (1, 2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[11.74674635  2.75388787  5.75875934  8.86100581  8.65543726  6.1143999
   5.88862202  4.0601076   1.01817062  2.27020792]]


**49. How to find the most frequent value in an array?**

In [7]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[5 0 6 3 4 2 2 2 1 1 8 9 9 8 5 0 4 0 0 9 3 9 2 3 8 8 6 4 1 6 8 6 7 0 4 7 2
 9 8 6 9 1 9 5 4 8 7 4 5 0]
8


**50.Extract all the contiguous 3x3 blocks from a random 10x10 matrix.**

In [109]:
import numpy as np
from numpy.lib import stride_tricks 
X = np.random.randint(0,5,(10,10))
n=3
i = 1 + (X.shape[0]-3)
j = 1 + (X.shape[1]-3)
C = stride_tricks.as_strided(X,shape=(i,j,n,n),strides=X.strides + X.strides)
print(C)

[[[[3 2 3]
   [4 1 1]
   [1 4 3]]

  [[2 3 0]
   [1 1 3]
   [4 3 4]]

  [[3 0 0]
   [1 3 0]
   [3 4 1]]

  [[0 0 1]
   [3 0 1]
   [4 1 4]]

  [[0 1 0]
   [0 1 2]
   [1 4 1]]

  [[1 0 4]
   [1 2 3]
   [4 1 2]]

  [[0 4 3]
   [2 3 3]
   [1 2 2]]

  [[4 3 4]
   [3 3 2]
   [2 2 4]]]


 [[[4 1 1]
   [1 4 3]
   [2 3 1]]

  [[1 1 3]
   [4 3 4]
   [3 1 2]]

  [[1 3 0]
   [3 4 1]
   [1 2 0]]

  [[3 0 1]
   [4 1 4]
   [2 0 0]]

  [[0 1 2]
   [1 4 1]
   [0 0 3]]

  [[1 2 3]
   [4 1 2]
   [0 3 2]]

  [[2 3 3]
   [1 2 2]
   [3 2 1]]

  [[3 3 2]
   [2 2 4]
   [2 1 3]]]


 [[[1 4 3]
   [2 3 1]
   [0 3 0]]

  [[4 3 4]
   [3 1 2]
   [3 0 3]]

  [[3 4 1]
   [1 2 0]
   [0 3 0]]

  [[4 1 4]
   [2 0 0]
   [3 0 2]]

  [[1 4 1]
   [0 0 3]
   [0 2 4]]

  [[4 1 2]
   [0 3 2]
   [2 4 4]]

  [[1 2 2]
   [3 2 1]
   [4 4 3]]

  [[2 2 4]
   [2 1 3]
   [4 3 4]]]


 [[[2 3 1]
   [0 3 0]
   [2 0 4]]

  [[3 1 2]
   [3 0 3]
   [0 4 3]]

  [[1 2 0]
   [0 3 0]
   [4 3 0]]

  [[2 0 0]
   [3 0 2]
   [3 0 4]]

  [[0 0 3]
   

This code creates a 10×10 random matrix and then uses stride_tricks.as_strided to generate all overlapping 3×3 submatrices

**51.Consider a 16x16 array, how to get the block-sum(block size is 4x4)**

In [113]:
arr = np.ones((16,16))
p = 4 #block size
S = np.add.reduceat(np.add.reduceat(arr,np.arange(0,arr.shape[0],p),axis=0),
                                    np.arange(0,arr.shape[1],p),axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In this code 16 x 16 matrix divided into 4x4 blocks and computes the sum inside each block.

**52. How to get the nth largest values of an array?**

In [114]:
X = np.arange(10000)
np.random.shuffle(X)
n=5  #Top 5 largest elements
#slow
print(X[np.argsort(X)[-n:]])
#fast
print(X[np.argpartition(-X,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


np.argsort(X) returns the indices that would sort the array in ascending order and [n:] select the last n indices which corresspond to the largestn elements. it is slow because even if we need let's say 5 elements it will sort all elements.
np.argpartition(X) will negate all values to find the smallest values. so smallest in -X means largest in X.

**53. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).**

In [6]:
import numpy as np
A = np.random.randn(100)
N = 1000
index  = np.random.randint(0,A.size,(N,A.size))
mean = A[index].mean(axis=1)
print(f"Mean:\n{mean}")
confint = np.percentile(mean,[2.5,97.5])
print(confint)

Mean:
[ 1.32796063e-01  1.47056755e-01  2.35759102e-02  8.02826841e-02
 -9.98584488e-02 -1.16354120e-01 -1.30535639e-01  6.80150198e-02
  1.39214472e-02  1.38612432e-01  5.85985891e-02 -5.00215613e-03
  6.63588684e-02 -6.25566174e-03  1.13825457e-01  3.89047166e-02
  7.51353569e-02 -2.85922804e-02 -9.05057473e-02  7.77162632e-02
  9.55216896e-03  4.37578329e-02 -8.12122019e-03  1.28370093e-01
 -4.38982896e-02 -2.93589729e-02  1.34631006e-02 -4.83417699e-02
 -4.15869748e-02 -1.00350959e-01 -2.60373839e-02 -5.99881547e-02
  1.59533263e-02 -9.29970689e-02 -6.41594160e-02 -2.19802248e-02
  6.28433465e-02  5.05349250e-02 -2.10217660e-02 -8.08791126e-03
  2.02985469e-01 -2.83676092e-03 -6.50481815e-02 -6.60528597e-02
  1.35247894e-02 -1.52316322e-01  3.86678544e-02  8.12165137e-02
 -9.96818975e-03 -1.78048785e-02 -1.08358492e-01 -4.43233426e-02
 -2.08477744e-02 -1.27455774e-01 -1.65094326e-01 -3.35205943e-02
 -2.02020487e-01  1.87911581e-02 -1.05857815e-01  1.25030882e-01
  4.19596659e-03  1